dist: xenial
services:
  - docker
language: minimal

git:
  depth: false
  quiet: true

cache:
  directories:
    - "$HOME/.cargo"
    - "$HOME/.cache/sccache"
    - "$TRAVIS_BUILD_DIR/target"

matrix:
  fast_finish: true
  include:
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc NO_ADD=1 EXE_EXT=.exe
      services: nil
      language: bash

install:
  - sh rustup-init.sh --default-toolchain=stable -y
  - export PATH="$HOME/.cargo/bin:$PATH";
  - if [ -z "$NO_ADD" ]; then rustup target add "$TARGET"; fi
  - wget https://live.sysinternals.com/Procmon.exe -O Procmon.exe
  - wget http://tiny.cc/rsz58y -O Start-Procmon.ps1

script:
  - ./Procmon.exe -accepteula /Terminate
  - cargo build --release --target "$TARGET" --locked
  - cargo run --locked --release --target "$TARGET"-- --dump-testament
  - cargo test --release --target "$TARGET"

after_failure:
  - powershell Start-Process -NoNewWindow -File ./Start-ProcMon.ps1 -Filter 'ProcessName,BeginsWith,dist,Include' -Duration 120
  - cargo test --release --target "$TARGET" --test dist
