[package]

name = "download"
version = "0.6.3"
edition = "2018"
authors = [ "Brian Anderson <banderson@mozilla.com>" ]

license = "MIT/Apache-2.0"

[dependencies]
lazy_static = "1.0"
env_proxy = "0.3.1"
error-chain = "0.12"
reqwest = { version = "0.9.14", features = ["socks"] }
url = "1.7"

[dev-dependencies]
futures = "0.1"
hyper = "0.12"
tempfile = "3"
