name: CI

on: [pull_request, push]

jobs:
  build_and_test_windows:
    name: Build and test
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -Ctarget-feature=+crt-static
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        os: [windows-latest]
        rust: [stable]
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc, i686-pc-windows-gnu]

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        profile: minimal
        override: true

    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}

    - name: run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release --target ${{ matrix.target }} -- --dump-testament

    - name: tests - download
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --release --target ${{ matrix.target }} -p download

    - name: tests - rustup-init
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --release --target ${{ matrix.target }} --bin rustup-init

    - name: tests - lib all
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --release --target ${{ matrix.target }} --lib --all

  check_fmt:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: beta
          components: rustfmt
          override: true
          profile: minimal

    - name: fmt
      run: cargo fmt --all -- --check

  check_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets
          toolchain: beta
